### ISSUE TITLE
Provide an example with multiple path

### ISSUE THREAD

**Issue by tristanbes** [ansible/ansible-lint-action#10]
Hello,

The doc misses an example with multiple playbook linting;

Right now I've tried: 

```yaml
name: CI  # feel free to pick your own name

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: ansible-galaxy install -r roles/requirements.yml --force

    - name: Lint Ansible Playbook
      # replace "master" with any valid ref
      uses: ansible/ansible-lint-action@master
      with:
        # [required]
        # Paths to ansible files (i.e., playbooks, tasks, handlers etc..)
        # or valid Ansible directories according to the Ansible role
        # directory structure.
        targets:
          - "playbook-example.yml"
          - "playbook-provisionning.yml"
```

But Github says that 

```
### ERRORED 13:29:06Z

- Your workflow file was invalid: The pipeline is not valid. .github/workflows/ci.yml (Line: 26, Col: 11): A sequence was not expected
```
