### ISSUE TITLE
config ignored ?

### ISSUE THREAD

**Issue by diepes** [ansible/ansible-lint-action#167]
Added a config file to my git-repo

.config/ansible-lint.yml

It works locally when I change the profile in the config.
The GitHub action does not use the config file.

Action
```
...
      - name: Run ansible-lint
        # replace `main` with any valid ref, or tags like `v6`
        uses: ansible/ansible-lint-action@v6.15.0
...
```
![image](https://user-images.githubusercontent.com/96414/236997365-a21fb32b-a17b-4deb-9000-5a538cffb904.png)

**Comment by till** [comment]
Had a similar problem, but last time I checked, it was supposed to be `.config/ansible-lint` but that doesn't seem to work either anymore. Probably (yet) another change in ansible-lint that I missed. ;) [Excuse my snarkyness.]

I went back to an older version of the action and pinned it — see below, and now my workflow runs.

This is how:

```yaml
# .config/ansible-lint.yml
skip_list:
  - experimental
  - fqcn-builtins
```

My workflow contains this:

```yaml
jobs:
  ansible_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ansible-community/ansible-lint-action@v6.3.0
        with:
          path: "ansible/"
```

If you still have issues, I would suggest to test with [act](https://github.com/nektos/act) locally as it saves you some time waiting for actions to run.
