### ISSUE TITLE
requirements.yml not loaded from given path

### ISSUE THREAD

**Issue by teal-bauer** [ansible/ansible-lint-action#177]
I have a repo where the ansible files, including the requirements.yml, are in a subdirectory named "ansible". I call this action in a workflow as follows;

```yaml
      - name: Run ansible-lint
        # replace `main` with any valid ref, or tags like `v6`
        uses: ansible/ansible-lint-action@main
        with:
          path: "ansible/"
```

However, it fails with errors like

```
couldn't resolve module/action 'community.general.dpkg_divert'. 
```

The `community.general` collection is specified in ansible/requirements.yml:

```yaml
---
roles:
  - src: monolithprojects.github_actions_runner

collections:
  - name: ansible.posix
  - name: community.docker
  - name: community.general
```

but it does not seem to be installed or recognized.

Additionally, ansible-lint does not appear to find its config if it's not in the repo root.
