### ISSUE TITLE
ansible-lint fails validating the .github/workflows/ansible-lint.yml

### ISSUE THREAD

**Issue by johanneskastl** [ansible/ansible-lint-action#178]
I am not sure if the GitHub UI is lying, but it looks like ansible-lint is failing when validating the `.github/workflows/ansible-lint.yml` file.

https://github.com/johanneskastl/ansible-role-RedHat_install_epel-release/actions/runs/5641060520

```
Annotations
1 error

 yaml[truthy]: .github/workflows/ansible-lint.yml#L2
Truthy value should be one of \[false, true]
```

There is no truthy value in line 2 of that file:
https://github.com/johanneskastl/ansible-role-RedHat_install_epel-release/blob/main/.github/workflows/ansible-lint.yml#L2

Any ideas what goes wrong here?

**Comment by thozza** [comment]
I'm seeing the same thing in https://github.com/osbuild/ansible-osbuild-worker/actions/runs/5693484101/job/15432675093?pr=4

**Comment by johanneskastl** [comment]
At least there is a workaround (in my case for a single role):

```yaml
      - name: Run ansible-lint
        # replace `main` with any valid ref, or tags like `v6`
        uses: ansible/ansible-lint-action@main
        with:
          path: "tasks/main.yml"
```

Limiting the scope to the role's `tasks/main.yml` file ignores the `.github/workflows/` file(s).
