### ISSUE TITLE
Lint is failing with "echo 'ERROR: Unsupported flag: '\''-x skip_ansible_lint'\'''"

### ISSUE THREAD

**Issue by samitpal** [ansible/ansible-lint-action#22]
Seeing following error since the last 2-3 days. It has been working fine for the past few months. Did something hange?

```
+ : /github/workspace
+ pushd /github/workspace
+ local opts
++ parse_args '-x skip_ansible_lint'
++ local opts=
++ ((  1  ))
++ case "$1" in
++ echo 'ERROR: Unsupported flag: '\''-x skip_ansible_lint'\'''
ERROR: Unsupported flag: '-x skip_ansible_lint'
```

My workflow file is follows

```
name: Ansible Lint  # feel free to pick your own name

on:
  push:
    branches:
        - master
    paths:
      - 'ansible/**'
  pull_request:
    branches:
        - master
    paths:
      - 'ansible/**'

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
    - uses: actions/checkout@v2

    - name: Lint Ansible Playbook
      # replace "master" with any valid ref
      uses: ansible/ansible-lint-action@vmaster
      with:
        # [required]
        # Paths to ansible files (i.e., playbooks, tasks, handlers etc..)
        # or valid Ansible directories according to the Ansible role
        # directory structure.
        # If you want to lint multiple ansible files, use the following syntax
        # targets: |
        #   playbook_1.yml
        #   playbook_2.yml

        # TO-DO: See if the list can be dynamic ro regexp based
        targets: |
          ansible/alertmanager.yml

        # [optional]
        # Arguments to be passed to the ansible-lint

        # Options:
        #   -q                    quieter, although not silent output
        #   -p                    parseable output in the format of pep8
        #   --parseable-severity  parseable output including severity of rule
        #   -r RULESDIR           specify one or more rules directories using one or
        #                         more -r arguments. Any -r flags override the default
        #                         rules in ansiblelint/rules, unless -R is also used.
        #   -R                    Use default rules in ansiblelint/rules in addition to
        #                         any extra
        #                         rules directories specified with -r. There is no need
        #                         to specify this if no -r flags are used
        #   -t TAGS               only check rules whose id/tags match these values
        #   -x SKIP_LIST          only check rules whose id/tags do not match these
        #                         values
        #   --nocolor             disable colored output
        #   --exclude=EXCLUDE_PATHS
        #                         path to directories or files to skip. This option is
        #                         repeatable.
        #   -c C                  Specify configuration file to use. Defaults to ".ansible-lint"
        # skip_ansible_lint is used right now wherever we have the shell modules. linit complains about the shell
        # module use
        args: "-x skip_ansible_lint"
```
