### ISSUE TITLE
Proper version tagging

### ISSUE THREAD

**Issue by ruzickap** [ansible/ansible-lint-action#23]
Hello.

Would it be possible to do a proper tagging for this project please? 

Maybe good starting point is here: https://github.com/actions/checkout 
They are using versions like:

* `v2` -> `v2.0.0`
* `v4` -> `v4.1.0`

It would be really handy to use something like `v4` instead of specifying the exact version only `v4.1.0`:

```yaml
    - uses: ansible/ansible-lint-action@v4
```

Thank you...

**Comment by webknjaz** [comment]
I mean, we need to set up automation for this. But yes, it's possible. OTOH, relying on tags/branches is a security disaster for users FTR.

Are you up for contributing this?

**Comment by ruzickap** [comment]
It should not be so hard.

I'm using https://github.com/haya14busa/action-update-semver for it:

```yaml
name: update-semver

on:
  release:
    types: [published]
    tags:
      - 'v*.*.*'

jobs:
  update-semver:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Semver
        uses: haya14busa/action-update-semver@v1
        with:
          major_version_tag_only: true
          github_token: ${{ secrets.github_token }}
```

The example above ^^^ should be working...
