### ISSUE TITLE
Invalid requirement: 'ansible==2.9\nansible-lint==4.2.0'

### ISSUE THREAD

**Issue by vitabaks** [ansible/ansible-lint-action#27]
```yaml
    - name: Lint Ansible Playbook "ansible-role-pgcenter". Commit ${{ github.sha }}
      uses: ansible/ansible-lint-action@master
      with:
        targets: "tasks/main.yml"
        override-deps: |
          ansible==2.9
          ansible-lint==4.2.0
        args: ""
```
ERROR: Invalid requirement: 'ansible==2.9\nansible-lint==4.2.0'

<details><summary>Click here to expand...</summary><p>

```console
Run ansible/ansible-lint-action@master
  with:
    targets: tasks/main.yml
    override-deps: ansible==2.9
  ansible-lint==4.2.0
  
/usr/bin/docker run --name d00b330f87c91b840c44b5820966fbd82f6910_ea039c --label d00b33 --workdir /github/workspace --rm -e INPUT_TARGETS -e INPUT_OVERRIDE-DEPS -e INPUT_ARGS -e TARGETS -e OVERRIDE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/ansible-role-pgcenter/ansible-role-pgcenter":"/github/workspace" d00b33:0f87c91b840c44b5820966fbd82f6910  ""
/github/workspace /github/workspace
+ args=("$@")
+ '[' /entrypoint.sh = /entrypoint.sh ']'
+ echo -E '\nRunning Ansible Lint...\n'
\nRunning Ansible Lint...\n
+ ansible::lint ''
+ : tasks/main.yml
+ : /github/workspace
+ pushd /github/workspace
+ override_python_packages
+ [[ -n ansible==2.9
ansible-lint==4.2.0
 ]]
+ pip install 'ansible==2.9
ansible-lint==4.2.0
'
WARNING: The directory '/github/home/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
ERROR: Invalid requirement: 'ansible==2.9\nansible-lint==4.2.0'
+ echo 'Completed installing override dependencies...'
Completed installing override dependencies...
+ local opts
++ parse_args
++ local opts=
++ ((  0  ))
++ eval set -- ''
+++ set --
++ echo ''
++ return 0
+ opts=
+ ansible-lint -v --force-color tasks/main.yml
Examining tasks/main.yml of type playbook
Examining tasks/pgcenter.yml of type playbook
Examining tasks/bash_alias.yml of type playbook
```
</p></details>
