### ISSUE TITLE
Rule skip list argument not applied

### ISSUE THREAD

**Issue by bgauduch** [ansible/ansible-lint-action#29]
Hello there !

When using a rule number exclusion as an argument with this action, it looks like it's not applied.

here is my configuration:
```yaml
name: ansible-checks

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Lint .yml Ansible files
        uses: ansible/ansible-lint-action@master
        if: always()
        with:
          targets: "ansible/**/*.yml"
          override-deps: |
            ansible~=2.9.0
            ansible-lint~=4.2.0
          arg: "-x 204"
```

Here is redacted sample of the output log:
```bash
# many similar lines
[204] Lines should be no longer than 160 chars
ansible/redacted/path/file:XX
[redacted key: value]"
```

As we can see from the logs, rule 204 is still applied even if it is in the skip list.

Maybe related to #20  ?
