### ISSUE TITLE
Globing in target seems broken

### ISSUE THREAD

**Issue by bgauduch** [ansible/ansible-lint-action#30]
When using globing in targets, the linter dosn't work properly.

Exemple workflow:
```yaml
name: ansible-checks

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Lint .yml Ansible files
        uses: ansible/ansible-lint-action@master
        if: always()
        with:
          targets: "ansible/**/*.(yml|yaml)"
          override-deps: |
            ansible~=2.9.0
            ansible-lint~=4.2.0
          arg: "-x 204"
```

Github action logs extract:
```sh
[...]
+ ansible-lint -v --force-color 'ansible/**/*.(yml|yaml)'
WARNING: Couldn't open ansible/**/*.(yml|yaml) - No such file or directory
Examining ansible/**/*.(yml|yaml) of type playbook
[...]
```

When using the same target with ansible-lint CLI directly, it works without trouble.
Also tested with `*.{yml,yaml}`, same result.
