### ISSUE TITLE
Targets is not a valid input under with

### ISSUE THREAD

**Issue by robbell** [ansible/ansible-lint-action#38]
I've tried various iterations of the below, but all result in the same error `##[warning]Unexpected input(s) 'targets', valid inputs are ['entryPoint', 'args']`:

```yaml
    - name: ansible-lint
      uses: ansible/ansible-lint-action@v4.1.0.post0
      with:
        targets: "*.yml" # or "create-aks.yaml"
```

This appears to be the correct way to reference individual files according to documentation, but I've had a look at several other repos on GitHub who make use of `targets` and their builds all appear to fail with the same error.

I have had luck using the following:

```yaml
    - name: ansible-lint
      uses: ansible/ansible-lint-action@v4.1.0.post0
      env:
        ACTION_PLAYBOOK_NAME: create-aks.yaml
```
