### ISSUE TITLE
ImportError: cannot import name 'AnsibleCollectionLoader' from 'ansible.utils.collection_loader'

### ISSUE THREAD

**Issue by darthlukan** [ansible/ansible-lint-action#41]
As the title suggests, we're running into an issue whereby `ansible-lint` is unable to execute because of an import error. I'm unsure if this is an issue in our `workflow.yaml`, `ansible-lint-action`, or `ansible-lint` itself.

We noticed the issue 5 days ago but didn't look into it. Here is the output of the step in our workflow:

```
Run ansible/ansible-lint-action@master
  with:
    targets: ansible/playbook.yaml
  ansible/participants-setup.yaml
  ansible/participants-deploy.yaml
  
    override-deps: ansible==2.9
/usr/bin/docker run --name e5c3525f869eade1344f8bb774ab1a3f111c3_cea4b0 --label 1e5c35 --workdir /github/workspace --rm -e INPUT_TARGETS -e INPUT_OVERRIDE-DEPS -e INPUT_ARGS -e TARGETS -e OVERRIDE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/gitops-workshop/gitops-workshop":"/github/workspace" 1e5c35:25f869eade1344f8bb774ab1a3f111c3  ""
+ args=("$@")
+ '[' /entrypoint.sh = /entrypoint.sh ']'
+ echo -E '\nRunning Ansible Lint...\n'
\nRunning Ansible Lint...\n
+ ansible::lint ''
+ : 'ansible/playbook.yaml
ansible/participants-setup.yaml
ansible/participants-deploy.yaml
'
+ : /github/workspace
+ pushd /github/workspace
+ override_python_packages
+ [[ -n ansible==2.9 ]]
+ pip install ansible==2.9
/github/workspace /github/workspace
WARNING: The directory '/github/home/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting ansible==2.9
  Downloading ansible-2.9.0.tar.gz (14.1 MB)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.8/site-packages (from ansible==2.9) (2.11.2)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.8/site-packages (from ansible==2.9) (5.3.1)
Requirement already satisfied: cryptography in /usr/local/lib/python3.8/site-packages (from ansible==2.9) (3.1.1)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.8/site-packages (from jinja2->ansible==2.9) (1.1.1)
Requirement already satisfied: six>=1.4.1 in /usr/local/lib/python3.8/site-packages (from cryptography->ansible==2.9) (1.15.0)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in /usr/local/lib/python3.8/site-packages (from cryptography->ansible==2.9) (1.14.3)
Requirement already satisfied: pycparser in /usr/local/lib/python3.8/site-packages (from cffi!=1.11.3,>=1.8->cryptography->ansible==2.9) (2.20)
Building wheels for collected packages: ansible
  Building wheel for ansible (setup.py): started
  Building wheel for ansible (setup.py): finished with status 'done'
  Created wheel for ansible: filename=ansible-2.9.0-py3-none-any.whl size=16130179 sha256=7ecff50a9b01a2966b8f7add0152a27951566ad9565b0a45f1bd45b3534bd0e8
  Stored in directory: /tmp/pip-ephem-wheel-cache-5sfflf9p/wheels/d8/87/fb/65b7fd9034ef5f109d906139de22ea10259f98cbf5c4f73616
Successfully built ansible
Installing collected packages: ansible
  Attempting uninstall: ansible
    Found existing installation: ansible 2.10.0
    Uninstalling ansible-2.10.0:
      Successfully uninstalled ansible-2.10.0
Successfully installed ansible-2.9.0
+ pip check
WARNING: The directory '/github/home/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
No broken requirements found.
+ echo 'Completed installing override dependencies...'
Completed installing override dependencies...
+ local opts
++ parse_args
++ local opts=
++ ((  0  ))
++ eval set -- ''
+++ set --
++ echo ''
++ return 0
+ opts=
+ shopt -s globstar
+ ansible-lint -v --force-color ansible/playbook.yaml ansible/participants-setup.yaml ansible/participants-deploy.yaml
Traceback (most recent call last):
  File "/usr/local/bin/ansible-lint", line 5, in <module>
    from ansiblelint.__main__ import main
  File "/usr/local/lib/python3.8/site-packages/ansiblelint/__init__.py", line 22, in <module>
    from ansiblelint.rules import AnsibleLintRule
  File "/usr/local/lib/python3.8/site-packages/ansiblelint/rules/__init__.py", line 12, in <module>
    import ansiblelint.utils
  File "/usr/local/lib/python3.8/site-packages/ansiblelint/utils.py", line 38, in <module>
    from ansible.parsing.mod_args import ModuleArgsParser
  File "/usr/local/lib/python3.8/site-packages/ansible/parsing/mod_args.py", line 26, in <module>
    from ansible.plugins.loader import module_loader, action_loader
  File "/usr/local/lib/python3.8/site-packages/ansible/plugins/loader.py", line 25, in <module>
    from ansible.utils.collection_loader import AnsibleCollectionLoader, AnsibleFlatMapLoader, AnsibleCollectionRef
ImportError: cannot import name 'AnsibleCollectionLoader' from 'ansible.utils.collection_loader' (/usr/local/lib/python3.8/site-packages/ansible/utils/collection_loader/__init__.py)
```

And here is the content of our `.github/workflows/ansible-lint.yml`:

```
name: Ansible Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Run ansible-lint
    - name: ansible-lint
      uses: ansible/ansible-lint-action@master
      with:
        targets: |
          ansible/playbook.yaml
          ansible/participants-setup.yaml
          ansible/participants-deploy.yaml
        override-deps: ansible==2.9
        args: ""
        # args: |
        #   --exclude=ansible/files
        #   --exclude=ansible/vars
        #   --exclude=ansible/templates
        #   --exclude=ansible/requirements.yaml
```
