### ISSUE TITLE
Linting is not failing

### ISSUE THREAD

**Issue by polatsinan** [ansible/ansible-lint-action#58]
My workflow:
```yaml
name: Ansible Lint

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@master
      with:
        targets: tasks/main.yml
        override-deps: |
          ansible==2.10.0
          ansible-lint==4.2.0
          
        args: ""
```

Running locally:
```
# ansible-lint -v --force-color tasks/main.yml
Failed to guess project directory using git: fatal: Not a git repository (or any of the parent directories): .git
WARNING  Listing 4 violation(s) that are fatal
risky-file-permissions: File permissions unset or incorrect
tasks/main.yml:27 Task/Handler: Ensure SSL certificate

risky-file-permissions: File permissions unset or incorrect
tasks/main.yml:36 Task/Handler: Ensure SSL key

yaml: truthy value should be one of [false, true] (truthy)
tasks/main.yml:68

yaml: truthy value should be one of [false, true] (truthy)
tasks/main.yml:82

You can skip specific rules or tags by adding them to your configuration file:
# .ansible-lint
warn_list:  # or 'skip_list' to silence them completely
  - experimental  # all rules tagged as experimental
  - yaml  # Violations reported by yamllint

Finished with 2 failure(s), 2 warning(s) on 1 files.
#
```
As you can see, warnings are shown (as expected).

But when linting is being run via Github Actions I am not getting these warnings and the checks are succesfull while I expect the same warnings. See ([URL](https://github.com/polatsinan/postfix-server/runs/4715922421?check_suite_focus=true#step:4:80)):
```
+ shopt -s globstar
+ ansible-lint -v --force-color tasks/main.yml
Examining tasks/main.yml of type playbook
+ shopt -u globstar
```
